// Code generated by protoc-gen-go. DO NOT EDIT.
// source: DataFormat.proto

package dataformat

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Distribution struct {
	Min                  int64    `protobuf:"varint,1,opt,name=min,proto3" json:"min,omitempty"`
	Max                  int64    `protobuf:"varint,2,opt,name=max,proto3" json:"max,omitempty"`
	Mean                 float64  `protobuf:"fixed64,3,opt,name=mean,proto3" json:"mean,omitempty"`
	StdDev               float64  `protobuf:"fixed64,4,opt,name=std_dev,json=stdDev,proto3" json:"std_dev,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Distribution) Reset()         { *m = Distribution{} }
func (m *Distribution) String() string { return proto.CompactTextString(m) }
func (*Distribution) ProtoMessage()    {}
func (*Distribution) Descriptor() ([]byte, []int) {
	return fileDescriptor_f338bfeebed1f6b5, []int{0}
}

func (m *Distribution) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Distribution.Unmarshal(m, b)
}
func (m *Distribution) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Distribution.Marshal(b, m, deterministic)
}
func (m *Distribution) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Distribution.Merge(m, src)
}
func (m *Distribution) XXX_Size() int {
	return xxx_messageInfo_Distribution.Size(m)
}
func (m *Distribution) XXX_DiscardUnknown() {
	xxx_messageInfo_Distribution.DiscardUnknown(m)
}

var xxx_messageInfo_Distribution proto.InternalMessageInfo

func (m *Distribution) GetMin() int64 {
	if m != nil {
		return m.Min
	}
	return 0
}

func (m *Distribution) GetMax() int64 {
	if m != nil {
		return m.Max
	}
	return 0
}

func (m *Distribution) GetMean() float64 {
	if m != nil {
		return m.Mean
	}
	return 0
}

func (m *Distribution) GetStdDev() float64 {
	if m != nil {
		return m.StdDev
	}
	return 0
}

type RRP struct {
	RequestSize          int64    `protobuf:"varint,1,opt,name=request_size,json=requestSize,proto3" json:"request_size,omitempty"`
	ResponseSize         int64    `protobuf:"varint,2,opt,name=response_size,json=responseSize,proto3" json:"response_size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RRP) Reset()         { *m = RRP{} }
func (m *RRP) String() string { return proto.CompactTextString(m) }
func (*RRP) ProtoMessage()    {}
func (*RRP) Descriptor() ([]byte, []int) {
	return fileDescriptor_f338bfeebed1f6b5, []int{1}
}

func (m *RRP) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RRP.Unmarshal(m, b)
}
func (m *RRP) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RRP.Marshal(b, m, deterministic)
}
func (m *RRP) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RRP.Merge(m, src)
}
func (m *RRP) XXX_Size() int {
	return xxx_messageInfo_RRP.Size(m)
}
func (m *RRP) XXX_DiscardUnknown() {
	xxx_messageInfo_RRP.DiscardUnknown(m)
}

var xxx_messageInfo_RRP proto.InternalMessageInfo

func (m *RRP) GetRequestSize() int64 {
	if m != nil {
		return m.RequestSize
	}
	return 0
}

func (m *RRP) GetResponseSize() int64 {
	if m != nil {
		return m.ResponseSize
	}
	return 0
}

type RRPs struct {
	Rrps                 []*RRP   `protobuf:"bytes,1,rep,name=rrps,proto3" json:"rrps,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RRPs) Reset()         { *m = RRPs{} }
func (m *RRPs) String() string { return proto.CompactTextString(m) }
func (*RRPs) ProtoMessage()    {}
func (*RRPs) Descriptor() ([]byte, []int) {
	return fileDescriptor_f338bfeebed1f6b5, []int{2}
}

func (m *RRPs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RRPs.Unmarshal(m, b)
}
func (m *RRPs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RRPs.Marshal(b, m, deterministic)
}
func (m *RRPs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RRPs.Merge(m, src)
}
func (m *RRPs) XXX_Size() int {
	return xxx_messageInfo_RRPs.Size(m)
}
func (m *RRPs) XXX_DiscardUnknown() {
	xxx_messageInfo_RRPs.DiscardUnknown(m)
}

var xxx_messageInfo_RRPs proto.InternalMessageInfo

func (m *RRPs) GetRrps() []*RRP {
	if m != nil {
		return m.Rrps
	}
	return nil
}

type Flow struct {
	ServerAddress        uint64        `protobuf:"varint,1,opt,name=server_address,json=serverAddress,proto3" json:"server_address,omitempty"`
	NumRrp               int64         `protobuf:"varint,2,opt,name=num_rrp,json=numRrp,proto3" json:"num_rrp,omitempty"`
	InterReq             *Distribution `protobuf:"bytes,3,opt,name=inter_req,json=interReq,proto3" json:"inter_req,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Flow) Reset()         { *m = Flow{} }
func (m *Flow) String() string { return proto.CompactTextString(m) }
func (*Flow) ProtoMessage()    {}
func (*Flow) Descriptor() ([]byte, []int) {
	return fileDescriptor_f338bfeebed1f6b5, []int{3}
}

func (m *Flow) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Flow.Unmarshal(m, b)
}
func (m *Flow) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Flow.Marshal(b, m, deterministic)
}
func (m *Flow) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Flow.Merge(m, src)
}
func (m *Flow) XXX_Size() int {
	return xxx_messageInfo_Flow.Size(m)
}
func (m *Flow) XXX_DiscardUnknown() {
	xxx_messageInfo_Flow.DiscardUnknown(m)
}

var xxx_messageInfo_Flow proto.InternalMessageInfo

func (m *Flow) GetServerAddress() uint64 {
	if m != nil {
		return m.ServerAddress
	}
	return 0
}

func (m *Flow) GetNumRrp() int64 {
	if m != nil {
		return m.NumRrp
	}
	return 0
}

func (m *Flow) GetInterReq() *Distribution {
	if m != nil {
		return m.InterReq
	}
	return nil
}

type Flows struct {
	Flows                []*Flow  `protobuf:"bytes,1,rep,name=flows,proto3" json:"flows,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Flows) Reset()         { *m = Flows{} }
func (m *Flows) String() string { return proto.CompactTextString(m) }
func (*Flows) ProtoMessage()    {}
func (*Flows) Descriptor() ([]byte, []int) {
	return fileDescriptor_f338bfeebed1f6b5, []int{4}
}

func (m *Flows) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Flows.Unmarshal(m, b)
}
func (m *Flows) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Flows.Marshal(b, m, deterministic)
}
func (m *Flows) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Flows.Merge(m, src)
}
func (m *Flows) XXX_Size() int {
	return xxx_messageInfo_Flows.Size(m)
}
func (m *Flows) XXX_DiscardUnknown() {
	xxx_messageInfo_Flows.DiscardUnknown(m)
}

var xxx_messageInfo_Flows proto.InternalMessageInfo

func (m *Flows) GetFlows() []*Flow {
	if m != nil {
		return m.Flows
	}
	return nil
}

type Session struct {
	ClientAddress        uint64        `protobuf:"varint,1,opt,name=client_address,json=clientAddress,proto3" json:"client_address,omitempty"`
	NumServers           int64         `protobuf:"varint,2,opt,name=num_servers,json=numServers,proto3" json:"num_servers,omitempty"`
	NumFlows             int64         `protobuf:"varint,3,opt,name=num_flows,json=numFlows,proto3" json:"num_flows,omitempty"`
	InterFlow            *Distribution `protobuf:"bytes,4,opt,name=inter_flow,json=interFlow,proto3" json:"inter_flow,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Session) Reset()         { *m = Session{} }
func (m *Session) String() string { return proto.CompactTextString(m) }
func (*Session) ProtoMessage()    {}
func (*Session) Descriptor() ([]byte, []int) {
	return fileDescriptor_f338bfeebed1f6b5, []int{5}
}

func (m *Session) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Session.Unmarshal(m, b)
}
func (m *Session) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Session.Marshal(b, m, deterministic)
}
func (m *Session) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Session.Merge(m, src)
}
func (m *Session) XXX_Size() int {
	return xxx_messageInfo_Session.Size(m)
}
func (m *Session) XXX_DiscardUnknown() {
	xxx_messageInfo_Session.DiscardUnknown(m)
}

var xxx_messageInfo_Session proto.InternalMessageInfo

func (m *Session) GetClientAddress() uint64 {
	if m != nil {
		return m.ClientAddress
	}
	return 0
}

func (m *Session) GetNumServers() int64 {
	if m != nil {
		return m.NumServers
	}
	return 0
}

func (m *Session) GetNumFlows() int64 {
	if m != nil {
		return m.NumFlows
	}
	return 0
}

func (m *Session) GetInterFlow() *Distribution {
	if m != nil {
		return m.InterFlow
	}
	return nil
}

type Sessions struct {
	Sessions             []*Session `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Sessions) Reset()         { *m = Sessions{} }
func (m *Sessions) String() string { return proto.CompactTextString(m) }
func (*Sessions) ProtoMessage()    {}
func (*Sessions) Descriptor() ([]byte, []int) {
	return fileDescriptor_f338bfeebed1f6b5, []int{6}
}

func (m *Sessions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Sessions.Unmarshal(m, b)
}
func (m *Sessions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Sessions.Marshal(b, m, deterministic)
}
func (m *Sessions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Sessions.Merge(m, src)
}
func (m *Sessions) XXX_Size() int {
	return xxx_messageInfo_Sessions.Size(m)
}
func (m *Sessions) XXX_DiscardUnknown() {
	xxx_messageInfo_Sessions.DiscardUnknown(m)
}

var xxx_messageInfo_Sessions proto.InternalMessageInfo

func (m *Sessions) GetSessions() []*Session {
	if m != nil {
		return m.Sessions
	}
	return nil
}

type User struct {
	ClientAddress        uint64        `protobuf:"varint,1,opt,name=client_address,json=clientAddress,proto3" json:"client_address,omitempty"`
	NumSessions          int64         `protobuf:"varint,2,opt,name=num_sessions,json=numSessions,proto3" json:"num_sessions,omitempty"`
	InterSession         *Distribution `protobuf:"bytes,3,opt,name=inter_session,json=interSession,proto3" json:"inter_session,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_f338bfeebed1f6b5, []int{7}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetClientAddress() uint64 {
	if m != nil {
		return m.ClientAddress
	}
	return 0
}

func (m *User) GetNumSessions() int64 {
	if m != nil {
		return m.NumSessions
	}
	return 0
}

func (m *User) GetInterSession() *Distribution {
	if m != nil {
		return m.InterSession
	}
	return nil
}

type Users struct {
	Users                []*User  `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Users) Reset()         { *m = Users{} }
func (m *Users) String() string { return proto.CompactTextString(m) }
func (*Users) ProtoMessage()    {}
func (*Users) Descriptor() ([]byte, []int) {
	return fileDescriptor_f338bfeebed1f6b5, []int{8}
}

func (m *Users) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Users.Unmarshal(m, b)
}
func (m *Users) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Users.Marshal(b, m, deterministic)
}
func (m *Users) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Users.Merge(m, src)
}
func (m *Users) XXX_Size() int {
	return xxx_messageInfo_Users.Size(m)
}
func (m *Users) XXX_DiscardUnknown() {
	xxx_messageInfo_Users.DiscardUnknown(m)
}

var xxx_messageInfo_Users proto.InternalMessageInfo

func (m *Users) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

func init() {
	proto.RegisterType((*Distribution)(nil), "dataformat.Distribution")
	proto.RegisterType((*RRP)(nil), "dataformat.RRP")
	proto.RegisterType((*RRPs)(nil), "dataformat.RRPs")
	proto.RegisterType((*Flow)(nil), "dataformat.Flow")
	proto.RegisterType((*Flows)(nil), "dataformat.Flows")
	proto.RegisterType((*Session)(nil), "dataformat.Session")
	proto.RegisterType((*Sessions)(nil), "dataformat.Sessions")
	proto.RegisterType((*User)(nil), "dataformat.User")
	proto.RegisterType((*Users)(nil), "dataformat.Users")
}

func init() { proto.RegisterFile("DataFormat.proto", fileDescriptor_f338bfeebed1f6b5) }

var fileDescriptor_f338bfeebed1f6b5 = []byte{
	// 444 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x53, 0xd1, 0x6a, 0xd4, 0x40,
	0x14, 0x25, 0x26, 0xdd, 0x6e, 0x6f, 0xb2, 0x75, 0x19, 0x1f, 0x0c, 0xf8, 0xe0, 0x36, 0xa5, 0xb2,
	0x20, 0x6c, 0xa1, 0x22, 0x3e, 0x88, 0x0f, 0xc2, 0xd2, 0x37, 0x61, 0x99, 0xc5, 0xe7, 0x30, 0x35,
	0xb7, 0x30, 0xd0, 0x4c, 0xb2, 0x73, 0x27, 0x6b, 0x29, 0xf8, 0x0d, 0x7e, 0x86, 0xbf, 0x29, 0x33,
	0x77, 0x56, 0x83, 0x88, 0xf6, 0xed, 0x72, 0xee, 0xb9, 0x39, 0xe7, 0xcc, 0x21, 0x30, 0x5f, 0x2b,
	0xa7, 0xae, 0x3b, 0xdb, 0x2a, 0xb7, 0xea, 0x6d, 0xe7, 0x3a, 0x01, 0x8d, 0x72, 0xea, 0x36, 0x20,
	0x55, 0x0d, 0xc5, 0x5a, 0x93, 0xb3, 0xfa, 0x66, 0x70, 0xba, 0x33, 0x62, 0x0e, 0x69, 0xab, 0x4d,
	0x99, 0x2c, 0x92, 0x65, 0x2a, 0xfd, 0x18, 0x10, 0x75, 0x5f, 0x3e, 0x89, 0x88, 0xba, 0x17, 0x02,
	0xb2, 0x16, 0x95, 0x29, 0xd3, 0x45, 0xb2, 0x4c, 0x64, 0x98, 0xc5, 0x73, 0x38, 0x26, 0xd7, 0xd4,
	0x0d, 0xee, 0xcb, 0x2c, 0xc0, 0x13, 0x72, 0xcd, 0x1a, 0xf7, 0xd5, 0x27, 0x48, 0xa5, 0xdc, 0x88,
	0x33, 0x28, 0x2c, 0xee, 0x06, 0x24, 0x57, 0x93, 0x7e, 0xc0, 0x28, 0x90, 0x47, 0x6c, 0xab, 0x1f,
	0x50, 0x9c, 0xc3, 0xcc, 0x22, 0xf5, 0x9d, 0x21, 0x64, 0x0e, 0x4b, 0x16, 0x07, 0xd0, 0x93, 0xaa,
	0xd7, 0x90, 0x49, 0xb9, 0x21, 0x71, 0x0e, 0x99, 0xb5, 0x3d, 0x95, 0xc9, 0x22, 0x5d, 0xe6, 0x57,
	0x4f, 0x57, 0xbf, 0x23, 0xad, 0xa4, 0xdc, 0xc8, 0xb0, 0xac, 0xbe, 0x41, 0x76, 0x7d, 0xd7, 0x7d,
	0x15, 0x17, 0x70, 0x4a, 0x68, 0xf7, 0x68, 0x6b, 0xd5, 0x34, 0x16, 0x89, 0x82, 0x7c, 0x26, 0x67,
	0x8c, 0x7e, 0x64, 0xd0, 0x67, 0x30, 0x43, 0x5b, 0x5b, 0xdb, 0x47, 0xe9, 0x89, 0x19, 0x5a, 0x69,
	0x7b, 0xf1, 0x16, 0x4e, 0xb4, 0x71, 0x68, 0x6b, 0x8b, 0xbb, 0x90, 0x3a, 0xbf, 0x2a, 0xc7, 0x8a,
	0xe3, 0x17, 0x94, 0xd3, 0x40, 0x95, 0xb8, 0xab, 0x2e, 0xe1, 0xc8, 0xcb, 0x93, 0x78, 0x05, 0x47,
	0xb7, 0x7e, 0x88, 0x6e, 0xe7, 0xe3, 0x5b, 0xcf, 0x90, 0xbc, 0xae, 0x7e, 0x24, 0x70, 0xbc, 0x45,
	0x22, 0x5f, 0xc4, 0x05, 0x9c, 0x7e, 0xb9, 0xd3, 0x68, 0xdc, 0x9f, 0x9e, 0x19, 0x3d, 0x78, 0x7e,
	0x09, 0xb9, 0xf7, 0xcc, 0x41, 0x28, 0xfa, 0x06, 0x33, 0xb4, 0x5b, 0x46, 0xc4, 0x0b, 0x38, 0xf1,
	0x04, 0xd6, 0x4f, 0xc3, 0x7a, 0x6a, 0x86, 0x96, 0x8d, 0xbd, 0x03, 0xe0, 0x60, 0x7e, 0x1d, 0x8a,
	0xfb, 0x57, 0x32, 0x7e, 0x04, 0x7f, 0x59, 0xbd, 0x87, 0x69, 0x34, 0x4a, 0xe2, 0x12, 0xa6, 0x14,
	0xe7, 0x18, 0xf0, 0xd9, 0xf8, 0x13, 0x91, 0x27, 0x7f, 0x91, 0xaa, 0xef, 0x09, 0x64, 0x9f, 0x09,
	0xed, 0x63, 0x33, 0x9e, 0x41, 0xc1, 0x19, 0xa3, 0x08, 0x87, 0xcc, 0x43, 0xc8, 0xe8, 0xe1, 0x03,
	0xcc, 0x38, 0x48, 0x24, 0xfd, 0xb7, 0xa5, 0x22, 0xd0, 0xe3, 0xbd, 0x6f, 0xca, 0x1b, 0x0a, 0x4d,
	0x0d, 0x7e, 0xf8, 0x5b, 0x53, 0x9e, 0x21, 0x79, 0x7d, 0x33, 0x09, 0x7f, 0xd2, 0x9b, 0x9f, 0x01,
	0x00, 0x00, 0xff, 0xff, 0xf2, 0xd7, 0x15, 0x53, 0x5d, 0x03, 0x00, 0x00,
}
